--- MERCREAR (TWEAKED BY MIXER 2007) ---
MercRear_x = {
	PropertiesInstance = {
		sightrange = 110,
		soundrange = 10,	-- rememeber that sound ranges intersect and sound range for AI doubles when in alert
		aibehavior_behaviour = "Job_StandIdle",
		groupid = 158,
		bHelmetOnStart = 0,
		fileHelmetModel = "",
		specialInfo= "",
		bHasLight = 0,
		bGunReady = 1,
		},

	Properties = {
		KEYFRAME_TABLE = "MUTANT_STEALTH",
		SOUND_TABLE = "",
		suppressedThrhld = 5.5,
		bSleepOnSpawn = 1,
		bAffectSOM = 1,
		bHasArmor = 1,

		bSmartMelee = 0,

		aggression = 0.6,	-- 0 = passive, 1 = total aggression

		commrange = 30.0,
		attackrange = 150,
		horizontal_fov = 130,
		eye_height = 2.1,
		forward_speed = 1.27,
		back_speed = 1.27,
		max_health = 244,
		accuracy = 0.6,
		responsiveness = 7.5,
		species = 100,
		special = 0,

		fSpeciesHostility = 2,
		fGroupHostility = 0,
		fPersistence = 0.5,
		equipEquipment = "P90",
		equipDropPack = "P90",
		AnimPack = "Basic",
		SoundPack = "",
		aicharacter_character = "Rear",
		pathname = "",
		pathsteps = 0,
		pathstart = 26,
		ReinforcePoint = "",
		fileModel = "Objects/characters/Mutants/mutant_stealth/mutant_stealth.cgf",
		bTrackable=1,
		speed_scales={
			run	=3.5,
			crouch	=.8,
			prone	=.5,
			xrun	=1.5,
			xwalk	=.81,
			rrun	=3.63,
			rwalk	=.94,
			},
		AniRefSpeeds = {
			WalkFwd = 1.27,
			WalkSide = 1.22,
			WalkBack = 1.29,
			WalkRelaxedFwd = 1.0487,
			WalkRelaxedSide = 1.22,
			WalkRelaxedBack = 1.04,
			XWalkFwd = 1.2,
			XWalkSide = 1.0, 
			XWalkBack = 0.94,
			XRunFwd = 4.5,
			XRunSide = 3.5, 
			XRunBack = 4.5,
			RunFwd = 4.62,
			RunSide = 3.57,
			RunBack = 4.62,
			CrouchFwd = 1.02,
			CrouchSide = 1.02,
			CrouchBack = 1.04,
	},
	},

	PhysParams = {
		mass = 80,
		height = 1.8,
		eyeheight = 1.7,
		sphereheight = 1.2,
		radius = 0.45,
	},

--pe_player_dimensions structure
	PlayerDimNormal = {
		height = 1.8,
		eye_height = 1.7,
		ellipsoid_height = 1.2,
		x = 0.45,
		y = 0.45,
		z = 0.6,
	},
	PlayerDimCrouch = {
		height = 1.5,
		eye_height = 1.0,
		ellipsoid_height = 0.95,
		x = 0.45,
		y = 0.45,
		z = 0.5,
	},
	PlayerDimProne = {
		height = 0.4,
		eye_height = 0.5,
		ellipsoid_height = 0.35,
		x = 0.45,
		y = 0.45,
		z = 0.2,
	},

	DeadBodyParams = {
		sim_type = 1,
	  max_time_step = 0.025,
	  gravityz = -7.5,
	  sleep_speed = 0.025,
	  damping = 0.3,
	  freefall_gravityz = -9.81,
	  freefall_damping = 0.1,

	  lying_mode_ncolls = 4,
	  lying_gravityz = -5.0,
	  lying_sleep_speed = 0.065,
	  lying_damping = 1.0,
		
	  water_damping = 0.1,
	  water_resistance = 1000,
	},
	BulletImpactParams = {
    stiffness_scale = 73,
    max_time_step = 0.02
  },
	GrenadeType = "ProjFlashbangGrenade",

		SoundEvents={
			{"srunfwd",	9,			},
			{"srunfwd",	20,			},
			{"srunback",	3,			},
			{"srunback",	15,			},
			{"swalkback",   3,			},
			{"swalkback",   23,		},
			{"swalkfwd",     3,		},
			{"swalkfwd",    18,		},
			{"arunfwd",	9,			},
			{"arunfwd",	20,			},
			{"arunback",	3,			},
			{"arunback",	15,			},
			{"awalkback",   3,			},
			{"awalkback",   23,		},
			{"awalkfwd",     3,		},
			{"awalkfwd",    18,		},
			{"cwalkfwd",	4,			},
			{"cwalkfwd",	21,			},
			{"attack_melee1", 7, Sound:Load3DSound("SOUNDS/weapons/machete/fire1.wav",SOUND_UNSCALABLE,255,5,60)},
			{"attack_melee1", 15, Sound:Load3DSound("SOUNDS/weapons/machete/fire2.wav",SOUND_UNSCALABLE,255,5,60)},
			{"grenade", 63, Sound:Load3DSound("SOUNDS/weapons/machete/fire1.wav",SOUND_UNSCALABLE,255,5,60)},
			{"grenade", 67, Sound:Load3DSound("SOUNDS/mutants/cover/exert_7.wav",SOUND_UNSCALABLE,255,5,190)},
		},
}