--  Created By: Mixer
-- Description: CIS Intruders Voice
SOUNDPACK.mutantvoice = {
				
	CALL_ALARM = {
				{
				PROBABILITY = 250,
				soundFile = "languages/voicepacks/mutantvoice/alarm_alone_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "languages/voicepacks/mutantvoice/alarm_alone_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "languages/voicepacks/mutantvoice/alarm_alone_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "languages/voicepacks/mutantvoice/alarm_alone_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	CALL_ALARM_GROUP = {
				{
				PROBABILITY = 333,
				soundFile = "languages/voicepacks/mutantvoice/alarm_group_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "languages/voicepacks/mutantvoice/alarm_group_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "languages/voicepacks/mutantvoice/alarm_group_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	FIRST_HOSTILE_CONTACT = {
				{
				PROBABILITY = 166,
				soundFile = "Sounds/mutants/cover/first_hostile_contact_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Sounds/mutants/cover/first_hostile_contact_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Sounds/mutants/cover/first_hostile_contact_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Sounds/mutants/cover/first_hostile_contact_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Sounds/mutants/cover/first_hostile_contact_5.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Sounds/mutants/cover/first_hostile_contact_6.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Sounds/mutants/cover/first_hostile_contact_7.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Sounds/mutants/cover/first_hostile_contact_8.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Sounds/mutants/cover/first_hostile_contact_9.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Sounds/mutants/cover/first_hostile_contact_10.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	FIRST_HOSTILE_CONTACT_GROUP = {
				{
				PROBABILITY = 166,
				soundFile = "Sounds/mutants/cover/first_hostile_contact_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Sounds/mutants/cover/first_hostile_contact_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Sounds/mutants/cover/first_hostile_contact_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Sounds/mutants/cover/first_hostile_contact_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Sounds/mutants/cover/first_hostile_contact_5.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Sounds/mutants/cover/first_hostile_contact_6.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Sounds/mutants/cover/first_hostile_contact_7.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Sounds/mutants/cover/first_hostile_contact_8.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Sounds/mutants/cover/first_hostile_contact_9.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 166,
				soundFile = "Sounds/mutants/cover/first_hostile_contact_10.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	THREATEN = {
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/threaten_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/threaten_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/threaten_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/threaten_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/threaten_5.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/threaten_6.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/threaten_7.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/threaten_8.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/threaten9.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	THREATEN_GROUP = {
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/threaten_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/threaten_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/threaten_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/threaten_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/threaten_5.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/threaten_6.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/threaten_7.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/threaten_8.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/threaten9.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	ENEMY_TARGET_LOST = {
				{
				PROBABILITY = 125,
				soundFile = "Sounds/mutants/cover/enemy_target_lost_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Sounds/mutants/cover/enemy_target_lost_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Sounds/mutants/cover/enemy_target_lost_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Sounds/mutants/cover/enemy_target_lost_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Sounds/mutants/cover/enemy_target_lost_5.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
	ENEMY_TARGET_LOST_GROUP = {
				{
				PROBABILITY = 125,
				soundFile = "Sounds/mutants/cover/enemy_target_lost_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Sounds/mutants/cover/enemy_target_lost_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Sounds/mutants/cover/enemy_target_lost_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Sounds/mutants/cover/enemy_target_lost_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 125,
				soundFile = "Sounds/mutants/cover/enemy_target_lost_5.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
	RETREATING_NOW = {
				{
				PROBABILITY = 333,
				soundFile = "languages/voicepacks/mutantvoice/comm_retreat_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "languages/voicepacks/mutantvoice/comm_retreat_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "languages/voicepacks/mutantvoice/comm_retreat_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
					
	PROVIDING_COVER = {
				{
				PROBABILITY = 333,
				soundFile = "languages/voicepacks/mutantvoice/comm_suppress_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "languages/voicepacks/mutantvoice/comm_suppress_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 333,
				soundFile = "languages/voicepacks/mutantvoice/comm_suppress_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
	FIRE_IN_THE_HOLE = {
				{
				PROBABILITY = 250,
				soundFile = "Sounds/mutants/cover/fire_in_the_hole_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Sounds/mutants/cover/fire_in_the_hole_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Sounds/mutants/cover/fire_in_the_hole_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Sounds/mutants/cover/fire_in_the_hole_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Sounds/mutants/cover/fire_in_the_hole_5.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
						

	IDLE_TO_INTERESTED = {
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/stay_alert_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/stay_alert_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/stay_alert_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/stay_alert_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	IDLE_TO_INTERESTED_GROUP = {
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/stay_alert_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/stay_alert_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/stay_alert_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 111,
				soundFile = "Sounds/mutants/cover/stay_alert_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
	
	
	FRIEND_DEATH = {
				{
				PROBABILITY = 250,
				soundFile = "Sounds/mutants/cover/respond_down_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Sounds/mutants/cover/respond_down_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Sounds/mutants/cover/respond_down_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Sounds/mutants/cover/respond_down_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	FRIEND_DEATH_GROUP = {
				{
				PROBABILITY = 250,
				soundFile = "Sounds/mutants/cover/respond_down_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Sounds/mutants/cover/respond_down_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Sounds/mutants/cover/respond_down_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 250,
				soundFile = "Sounds/mutants/cover/respond_down_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	GETTING_SHOT_AT = {
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/enemy_target_regain_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/enemy_target_regain_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/enemy_target_regain_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/enemy_target_regain_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/enemy_target_regain_5.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
			
	GETTING_SHOT_AT_GROUP = {
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/enemy_target_regain_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/enemy_target_regain_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/enemy_target_regain_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/enemy_target_regain_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/enemy_target_regain_5.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
	GET_REINFORCEMENTS = {
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/pointing_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/pointing_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/pointing_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/pointing_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/pointing_5.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
CALL_REINFORCEMENTS = {
			{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/call_reinforcements_1.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/call_reinforcements_2.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/call_reinforcements_3.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/call_reinforcements_4.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/call_reinforcements_5.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/call_reinforcements_6.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
				{
				PROBABILITY = 200,
				soundFile = "Sounds/mutants/cover/call_reinforcements_7.wav",
				Volume = 255,
				min = 12,
				max = 200,
				sound_unscalable = 0,
				},
			},
}